name: Multi OS

# Trigger the workflow on push or pull request
on: workflow_dispatch

jobs:
  multi-os:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9
      - name: uname
        run: |
            uname -a
      - name: Check Python version
        run: |
            python --version