name: Self-hosted

# Trigger the workflow on push or pull request
on: workflow_dispatch

jobs:
  prepare:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9
      - name: "pip3 install"
        run: |
          pip3 install --user -r requirements.txt
      - name: Check Python version
        run: |
          python --version
      - name: Check python modules
        run: |
          pip3 list
