name: Tests

# Trigger the workflow on push or pull request
on: workflow_dispatch

jobs:
  # distribution-check:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: rockylinux/rockylinux:9
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Are we really on Rocky Linux?
  #     run: |
  #       cat /etc/os-release
  multi-os:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9
      - name: uname
        run: |
            uname -a
      - name: Check Python version
        run: |
            python --version
